version: "3.9"  # Specify the Docker Compose version

services:  # This starts the services section
  build-rms:  # Name of the service
    build:  # Build configuration
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory
    image: juayweitian81/rms-docker-img:v4  # Name and tag of the Docker image
    container_name: rms-docker-container  
    ports:
      - "8000:5050"  
