apiVersion: v1
kind: Service
metadata: # Metadata about the Service
  name: rms-service
spec: # Defines the desired state of the Service
  selector: # Matches the labels of the pods this service will target
    app: rms-docker-img
  ports: # Defines how the service handles incoming traffic and exposed ports
  - protocol: TCP # Standard protocol for most web applications
    port: 80 # Exposes port 80, which is the default HTTP port
    targetPort: 5050 # Specifies the port the application listens on
  type: LoadBalancer # Expose the service externally using a public IP
